# This workflow will install and run flake8, runs on the self-hosted raspberry pi I have. 

name: Auto Self-Hosted flake8 lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  auto-lint:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install flake8
        if [ -f requirements_dev.txt ]; then python3.7 -m pip install -r requirements_dev.txt; fi
    - name: Lint with flake8
      run: |
        # Perform sanity check on the code (aka, check for syntax/undefined reference errors)
        python3.7 -m flake8 . --config=flake8-sanity-check.cfg
        echo "Sanity Check done"
        # Perform style based check on the code
        python3.7 -m flake8 . --config=flake8-style-check.cfg
